project:
  type: website

website:
  title: "Dr. Marcus Immonen Hagley"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    left: "© 2025 Dr. Marcus Immonen Hagley"
    right: "Built with [Quarto](https://quarto.org/)"
  
format:
  html:
    theme: cosmo
    toc: true