project:
  type: website

website:
  title: "Paweł Białas"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    left: "© 2025 Paweł Białas"
    right: "Built with [Quarto](https://quarto.org/)"
  
format:
  html:
    theme: cosmo
    toc: true